/**
 * PostgreSQL DDL generator
 * Generates PostgreSQL-dialect DDL SQL statements
 */

import type {
  DDLGenerator,
  DDLResult,
  ColumnDefinition,
  AlterColumnOptions,
  IndexDefinition,
  ConstraintDefinition,
  EnumDefinition
} from './types'

function q(name: string): string {
  return `"${name}"`
}

function columnSQL(col: ColumnDefinition): string {
  const parts: string[] = [q(col.name)]

  // serial types are shorthand in PG
  const lowerType = col.type.toLowerCase()
  if (lowerType === 'serial' || lowerType === 'bigserial' || lowerType === 'smallserial') {
    parts.push(col.type.toUpperCase())
  } else if (col.autoIncrement) {
    // Non-serial with auto-increment: use GENERATED BY DEFAULT AS IDENTITY
    parts.push(col.type.toUpperCase())
    parts.push('GENERATED BY DEFAULT AS IDENTITY')
  } else {
    parts.push(col.type.toUpperCase())
  }

  if (col.nullable === false) {
    parts.push('NOT NULL')
  }

  if (col.default !== undefined) {
    parts.push(`DEFAULT ${col.default}`)
  }

  if (col.unique) {
    parts.push('UNIQUE')
  }

  if (col.references) {
    parts.push(`REFERENCES ${q(col.references.table)}(${q(col.references.column)})`)
  }

  return parts.join(' ')
}

export class PostgreSQLDDLGenerator implements DDLGenerator {
  // ── Table ──────────────────────────────────────────────────────────────

  createTable(table: string, columns: ColumnDefinition[]): DDLResult {
    const warnings: string[] = []
    const pkCols = columns.filter(c => c.primaryKey)
    const colDefs = columns.map(c => columnSQL(c))

    if (pkCols.length > 0) {
      colDefs.push(`PRIMARY KEY (${pkCols.map(c => q(c.name)).join(', ')})`)
    }

    const sql = `CREATE TABLE ${q(table)} (\n  ${colDefs.join(',\n  ')}\n);`
    return { sql, warnings }
  }

  dropTable(table: string): DDLResult {
    return { sql: `DROP TABLE ${q(table)};`, warnings: [] }
  }

  // ── Column ─────────────────────────────────────────────────────────────

  addColumn(table: string, column: ColumnDefinition): DDLResult {
    return {
      sql: `ALTER TABLE ${q(table)} ADD COLUMN ${columnSQL(column)};`,
      warnings: []
    }
  }

  dropColumn(table: string, column: string): DDLResult {
    return {
      sql: `ALTER TABLE ${q(table)} DROP COLUMN ${q(column)};`,
      warnings: []
    }
  }

  alterColumn(options: AlterColumnOptions): DDLResult {
    const statements: string[] = []
    const warnings: string[] = []
    const t = q(options.table)
    const c = q(options.column)

    if (options.type) {
      statements.push(
        `ALTER TABLE ${t} ALTER COLUMN ${c} TYPE ${options.type.toUpperCase()};`
      )
    }

    if (options.rename) {
      statements.push(
        `ALTER TABLE ${t} RENAME COLUMN ${c} TO ${q(options.rename)};`
      )
    }

    if (options.setDefault !== undefined) {
      statements.push(
        `ALTER TABLE ${t} ALTER COLUMN ${c} SET DEFAULT ${options.setDefault};`
      )
    }

    if (options.dropDefault) {
      statements.push(
        `ALTER TABLE ${t} ALTER COLUMN ${c} DROP DEFAULT;`
      )
    }

    if (options.setNullable) {
      statements.push(
        `ALTER TABLE ${t} ALTER COLUMN ${c} DROP NOT NULL;`
      )
    }

    if (options.dropNullable) {
      statements.push(
        `ALTER TABLE ${t} ALTER COLUMN ${c} SET NOT NULL;`
      )
    }

    if (statements.length === 0) {
      warnings.push('No alter operations specified')
    }

    return { sql: statements.join('\n'), warnings }
  }

  // ── Index ──────────────────────────────────────────────────────────────

  addIndex(index: IndexDefinition): DDLResult {
    const unique = index.unique ? 'UNIQUE ' : ''
    const name = index.name || `idx_${index.table}_${index.columns.join('_')}`
    const using = index.type ? ` USING ${index.type.toUpperCase()}` : ''
    const cols = index.columns.map(q).join(', ')

    return {
      sql: `CREATE ${unique}INDEX ${q(name)} ON ${q(index.table)}${using} (${cols});`,
      warnings: []
    }
  }

  dropIndex(indexName: string, _table?: string): DDLResult {
    return { sql: `DROP INDEX ${q(indexName)};`, warnings: [] }
  }

  // ── Constraint ─────────────────────────────────────────────────────────

  addConstraint(constraint: ConstraintDefinition): DDLResult {
    const t = q(constraint.table)
    const warnings: string[] = []

    switch (constraint.type) {
      case 'foreign_key': {
        const name = constraint.name || `fk_${constraint.table}_${constraint.column}`
        const onDelete = constraint.onDelete
          ? ` ON DELETE ${constraint.onDelete.toUpperCase().replace('_', ' ')}`
          : ''
        return {
          sql: `ALTER TABLE ${t} ADD CONSTRAINT ${q(name)} FOREIGN KEY (${q(constraint.column!)}) REFERENCES ${q(constraint.references!.table)}(${q(constraint.references!.column)})${onDelete};`,
          warnings
        }
      }
      case 'unique': {
        const name = constraint.name || `uq_${constraint.table}_${constraint.columns!.join('_')}`
        const cols = constraint.columns!.map(q).join(', ')
        return {
          sql: `ALTER TABLE ${t} ADD CONSTRAINT ${q(name)} UNIQUE (${cols});`,
          warnings
        }
      }
      case 'check': {
        const name = constraint.name || `ck_${constraint.table}`
        return {
          sql: `ALTER TABLE ${t} ADD CONSTRAINT ${q(name)} CHECK (${constraint.expression});`,
          warnings
        }
      }
    }
  }

  dropConstraint(table: string, constraintName: string): DDLResult {
    return {
      sql: `ALTER TABLE ${q(table)} DROP CONSTRAINT ${q(constraintName)};`,
      warnings: []
    }
  }

  // ── Enum ───────────────────────────────────────────────────────────────

  addEnum(definition: EnumDefinition): DDLResult {
    const vals = definition.values.map(v => `'${v}'`).join(', ')
    return {
      sql: `CREATE TYPE ${q(definition.name)} AS ENUM (${vals});`,
      warnings: []
    }
  }

  alterEnum(name: string, addValue: string): DDLResult {
    return {
      sql: `ALTER TYPE ${q(name)} ADD VALUE '${addValue}';`,
      warnings: ['PostgreSQL does not support removing enum values']
    }
  }

  dropEnum(name: string): DDLResult {
    return {
      sql: `DROP TYPE ${q(name)};`,
      warnings: ['Will fail if any column references this enum type']
    }
  }
}
